apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-password
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ if .Values.env.FTP_PASS }}
  ftp-password: {{ .Values.env.FTP_PASS  | b64enc | quote }}
  {{ else }}
  ftp-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
