apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vsftp.fullname  }}
spec:
  type: {{ .Values.service.type }}
  selector:
      app: vsftpd
  ports:
    - port: 21
      nodePort: {{ .Values.service.port }}
      targetPort: 21
      protocol: TCP
      name: vsftpd
# 下面都是被动端口除非端口冲突不需要修该。
    - port: 8200
      nodePort: 8200
      targetPort: 8200
      protocol: TCP
      name: vsftpd0
    - port: 8201
      nodePort: 8201
      targetPort: 8201
      protocol: TCP
      name: vsftpd1
    - port: 8202
      nodePort: 8202
      targetPort: 8202
      protocol: TCP
      name: vsftpd2
    - port: 8203
      nodePort: 8203
      targetPort: 8203
      protocol: TCP
      name: vsftpd3
    - port: 8204
      nodePort: 8204
      targetPort: 8204
      protocol: TCP
      name: vsftpd4
    - port: 8205
      nodePort: 8205
      targetPort: 8205
      protocol: TCP
      name: vsftpd5
