apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1 
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.7.30
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', '/entrypoint.sh' ]
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-passwd
              key: mysql-root-passwd
        ports:
        - containerPort: 3306
          name: mysql
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -u root -p${NEW_PASSWORD} -S /home/sock/mysql/tmp/mysql.sock
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - mountPath: /home/sock/mysql/data
          name: data
        - name: mysql-conf
          mountPath: /home/sock/mysql/etc/my.cnf
          subPath: my.cnf
      volumes:
      - name: mysql-conf
        configMap:
          name: mysql-cnf
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
         app: mysql
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "300Gi"
        storageClassName: "local-path"
