apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.fullname  }}
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  {{ .Values.nginx.worker_processes }};
    worker_cpu_affinity {{ .Values.nginx.worker_cpu_affinity }};
    
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    
    
    events {
        worker_connections  {{ .Values.nginx.worker_connections }};
    }
    
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
         autoindex_exact_size off;
        autoindex_localtime on;  
        charset utf-8,gbk;    
    
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
    
        access_log  /var/log/nginx/access.log  main;
    
        sendfile        on;
        
            keepalive_timeout  65;
        
        
                    include /etc/nginx/conf.d/*.conf;
                    }
  default.conf: |
    server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }    
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
     }
      {{- if .Values.hostPath.enabled }}
  app.conf: |
    server
        {
                listen 8877;
                location / {
                        root /data;
                        autoindex on;
                    #    index  index.html;
                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-Server $host;

                }
        access_log /var/log/nginx/app_acc.log main;
        error_log  /var/log/nginx/app_err.log  error;

       } 
      {{- end }}
