apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.fullname  }}
    
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx
  ports:
    - port: 80
      nodePort: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: 8877
      nodePort: {{ .Values.service.portapp }}
      targetPort: 8877
      protocol: TCP
      name: httpapp
